# -*- coding: utf-8 -*-
"""Miniproject(vdo).py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNNt2ATi4TL9qThnh6ZEcmTSihq_1-Ya
"""

!pip3 install tensorflow==1.13.1

!pip3 install opencv-python

!pip3 install keras==2.2.4

!pip3 install numpy==1.16.1

!pip3 install imageai --upgrade

from imageai.Detection import VideoObjectDetection
import os

execution_path = os.getcwd()

detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
detector.loadModel()
detections = detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path , "traffic-mini.mp4"),
                                             output_file_path=os.path.join(execution_path , "traffic-mini-d.mp4")
                                             , frames_per_second=29, log_progress=True)

for person in detections:
    import smtplib
    sender = 'pprakash3016@gmail.com'
    receiver  = 'ihskas.07@gmail.com'
    msg = 'An object is detected !!'
    username = 'pprakash3016@gmail.com'
    password = 'abhivita2016'
    server = smtplib.SMTP_SSL('smtp.gmail.com:465')
    server.ehlo()
    #server.starttls()
    server.login(username,password)
    server.sendmail(sender, receiver, msg)
    server.close()
print ('successfully sent the mail')